# Configs

title: "Michael's Profile"
name: "Profile for Michael Nebor"
email: 
url: "https://MichaelNebor.github.io"
baseurl: "/Michael-Nebor-Profile"
repository: "MichaelNebor/Michael-Nebor-Profile"
header:
image: /assets/images/Nebor_Michael_ProfilePicture.jpg

include:
  - _pages
  - assets
  - index.html
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "contrast"

# settings for author profile
author:
  name   : "Michael Nebor"
  avatar : "/assets/images/Nebor_Michael_ProfilePicture.jpg"
  bio    : "My name is Michael Nebor, I am a Financial Economics PhD student at Northern Illinois University. I am looking for academic research positions."
  location: "Naperville, Illinois"
  github : 
  linkedin: "michael-nebor-9192b8119"
  email  : "Mjnebor@gmail.com"


# # comments by disqus
#comments:
  #provider: "disqus"
  #disqus:
    #shortname: "pwills-com"

#analytics:
  #provider: "google"
  #google:
    #tracking_id: "UA-116208936-1"


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
